### ISSUE TITLE
Can it coexist with CounterStrikeSharp？

### ISSUE THREAD

**Issue by himenekocn** [KZGlobalTeam/cs2kz-metamod#112]
Tested that CS2kz will not be loaded when placed together, it seems that the same interface has been hooked.
But currently there are too few Metamod plugins available, So I would like to ask if there is any way to achieve coexistence between the two?

**Comment by zer0k-z** [comment]
Have you tried the `gameconfig` branch and see if it's compatible with cs#? Or did you do the steps written in the dev branch's readme to make it work with cs#?

Generally speaking, metamod plugins don't play well with each other regarding hooks and detours because there is no way to know what function the other plugin detoured. That goes for any two metamod plugins, and not just cs2kz/cs#.

**Comment by 5Dotsu** [comment]
I can confirm `gameconfig` branch to run with cs# when adding cs2kz to metaplugins.ini as written in the steps on dev branch
