### ISSUE TITLE
Is prestrafe enabled?

### ISSUE THREAD

**Issue by gprogramer12** [KZGlobalTeam/cs2kz-metamod#119]
First of all, thank you for making this plugin. I love KZ since cs1.6 and I am willing to open a server with this mod soon. If it happened that I made any money out of it, 100% would be donated to you.

Just recenlty installed this mod, with no others rather than the required metamod.

No prestrafe seems to be there... Is it a feature? Have I done something wrong?

**Comment by GameChaos** [comment]
type !mode ckz in chat

**Comment by gprogramer12** [comment]
Thank you. Is there any docs somewhere to find how to use the plugin once installed?

**Comment by gprogramer12** [comment]
Thank you very much. Please keep the good work.

How could I donate to support the project?

**Comment by GameChaos** [comment]
you can chuck zer0k (the main dev) some money here: https://ko-fi.com/zer0k

**Comment by gprogramer12** [comment]
Sir, I was willing to learn the framework of metamod but I can't find any solid docs about cs2....

Do you know where I can find docs for CS2? i really want to contribute to the community.

Thank you in advance!

**Comment by zer0k-z** [comment]
There's no solid docs about CS2 because everything is more or less just reverse engineering works by the community. 

The resources are scattered everywhere, most things are reverse engineered, the [cs2 hl2sdk branch](https://github.com/alliedmodders/hl2sdk/tree/cs2/) contains lots of them though. There's also this [schema dump repo](https://github.com/neverlosecc/source2sdk/blob/cs2/sdk/server.hpp) which gives you an idea of the properties of various classes (but not all of them). The most comprehensive CS2 metamod project that I'm aware of is [CS2Fixes](https://github.com/Source2ZE/CS2Fixes) from the zombie escape community. I'd say asking around in the [AlliedModders discord](https://discord.gg/HUc67zN) is a good idea.

For CS2KZ project specifically, the goal is to have feature parity with [GOKZ](https://github.com/KZGlobalTeam/gokz). I personally uses CS2Fixes stuff for general purpose features (no reason to reinvent the wheel, after all), with helps from the leaked code back in 2018 and the dota 2 dwarf server binary that got accidentally released around that period as well.

**Comment by gprogramer12** [comment]
Damn then... It is so sketchy... You guys must be fuckking genious.

I guess I will support only by donating.

Thank you for your work!
