### ISSUE TITLE
Suggestion: Adjust some convars to make acceleration feel better

### ISSUE THREAD

**Issue by LaplaceTor** [KZGlobalTeam/cs2kz-metamod#59]
sv_air_max_wishspeed 30 and sv_friction 5.2 as default but in 64T probably it should be 40-45 and 5.8
Otherwise you cannot gain enough speed to reach 270+LJ and much a lot slide in GOKZ

**Comment by zer0k-z** [comment]
I'm not a big fan of sv_air_max_wishspeed because it introduces side effects in edge cases, think of the iconic 30u/s ladder speed takeoff. I think trying to emulate 128t is a much better idea.

The friction shouldn't have anything to do with airstrafing though, for ground movement CSGO's KZT actually has lower friction with higher acceleration (6.5 instead of 5.5)

**Comment by LaplaceTor** [comment]
> I'm not a big fan of sv_air_max_wishspeed because it introduces side effects in edge cases, think of the iconic 30u/s ladder speed takeoff. I think trying to emulate 128t is a much better idea.
> 
> The friction shouldn't have anything to do with airstrafing though, for ground movement CSGO's KZT actually has lower friction with higher acceleration (6.5 instead of 5.5)

Alright , but about sv_friction , after try a lot map in this [https://steamcommunity.com/workshop/filedetails/?id=3082638465](url) workshop collection , i think it should change to another better settings

**Comment by GameChaos** [comment]
friction is actually tickrate independent (pretty sure), so there's no point in changing it

**Comment by zer0k-z** [comment]
> Alright , but about sv_friction , after try a lot map in this https://steamcommunity.com/workshop/filedetails/?id=3082638465 workshop collection , i think it should change to another better settings

The mappers should adjust to the new mode once it is finally finished, especially higher difficulty maps because the new mode will not be an exact replica of KZT or SKZ, rather somewhere inbetween (and it can't really do 1:1 anyway because of the game being on half the tickrate and some movement implementations being different between the two games, you can only get close)

**Comment by LaplaceTor** [comment]
> The mappers should adjust to the new mode once it is finally finished, especially higher difficulty maps because the new mode will not be an exact replica of KZT or SKZ, rather somewhere inbetween (and it can't really do 1:1 anyway because of the game being on half the tickrate and some movement implementations being different between the two games, you can only get close)

Anyway , is there a convar suggestion settings at the moment for 64T?

**Comment by zer0k-z** [comment]
`sv_air_max_wishspeed` and `sv_airaccelerate` is as good as it gets for the moment.
